name: Dev With Imagination
description: I like to develop things. This is a dumping ground of random thoughts.
url: http://www.devwithimagination.com

jobtitle: Software Developer
location: Scotland
email: david@devwithimagination.com
twitter: DavidHutchison

pygments: true
#markdown: rdiscount
markdown: kramdown
timezone: Europe/London
permalink: /:year/:month/:day/:title/
relative_permalinks: false
paginate: 5
gems:
- jekyll-redirect-from
- jekyll-sitemap

excerpt_separator: <!--more-->
drop_caps: false

exclude: [node_modules, assets/less]