name: Dev With Imagination
description: I like to develop things. This is a dumping ground of random thoughts.
url: http://www.devwithimagination.com

jobtitle: Software Developer
location: Scotland
email: david@devwithimagination.com

pygments: true
markdown: rdiscount
timezone: Europe/London
permalink: /:year/:month/:day/:title/
relative_permalinks: false