name: Dev With Imagination
description: I like to develop things. This is a dumping ground of random thoughts.
url: http://www.devwithimagination.com

jobtitle: Software Development Lead
location: Scotland
email: david@devwithimagination.com
author: david
twitter: 
  username: DavidHutchison

highlighter: rouge
markdown: kramdown
timezone: Europe/London
permalink: /:year/:month/:day/:title/
relative_permalinks: false
paginate: 5
plugins:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-feed

kramdown:
  parse_block_html: true

excerpt_separator: <!--more-->
drop_caps: false

# Include these files/folders that are excluded by default
include: [ "/.well-known" ]

exclude: [node_modules, assets/less]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      include_seo: true
  -
    scope:
      path: "archives"
      type: "pages"
    values:
      include_seo: true
