lang: en-GB
timezone: Europe/London

title: Dev With Imagination
tagline: I like to develop things.
description: >-
  A personal blog by David Hutchison about software, self-hosting, home
  automation, and the occasional side quest.

url: "https://www.devwithimagination.com"
baseurl: ""

github:
  username: dhutchison

twitter:
  username: DavidHutchison

social:
  name: David Hutchison
  email: david@devwithimagination.com
  links:
    - https://github.com/dhutchison
    - https://mastodon.scot/@davidhutchison
    - https://www.linkedin.com/in/david-hutchison-dev
    - https://about.devwithimagination.com

theme: jekyll-theme-chirpy

highlighter: rouge
markdown: kramdown
permalink: /:year/:month/:day/:title/

kramdown:
  parse_block_html: true
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /:year/:month/:day/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      dynamic_title: true
  - scope:
      path: "assets/images/404"
    values:
      swcache: false
  - scope:
      path: ""
      type: pages
    values:
      comments: false

plugins:
  - jekyll-archives
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

pagination:
  enabled: true
  per_page: 5
  permalink: /page/:num/
  title: ":title - page :num"
  sort_reverse: true

paginate: 5
paginate_path: /page/:num/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /archives/tags/:name/
    category: /archives/categories/:name/

feed:
  path: atom.xml

avatar: /images/self_square.jpg

analytics:
  google:
    id: G-ZWZMXJ0CPW

comments:
  provider: disqus
  disqus:
    shortname: devwithimagination

toc: true

include:
  - .well-known

exclude:
  - 404.html
  - node_modules
  - assets/less
  - _pre-theme
  - vendor
  - README.md
  - LICENSE
  - "*.gemspec"

sass:
  style: compressed
