name: Dev With Imagination
jobtitle: Software Developer
location: Scotland
email: david@devwithimagination.com
pygments: true
markdown: maruku
timezone: Europe/London
permalink: /blog/:categories/:year/:month/:day/:title/