name: Dev With Imagination
description: I like to develop things. This is a dumping ground of random thoughts.
url: http://www.devwithimagination.com

jobtitle: Software Development Lead
location: Scotland
email: david@devwithimagination.com
author: david
twitter: 
  username: DavidHutchison

highlighter: rouge
#markdown: rdiscount
markdown: kramdown
timezone: Europe/London
permalink: /:year/:month/:day/:title/
relative_permalinks: false
paginate: 5
gems:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-feed

excerpt_separator: <!--more-->
drop_caps: false

exclude: [node_modules, assets/less]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
