name: Dev With Imagination
title: Dev With Imagination
description: I like to develop things. This is a dumping ground of random thoughts.
url: http://www.devwithimagination.com

jobtitle: Software Development Lead
location: Scotland
email: david@devwithimagination.com
author: david
twitter: 
  username: DavidHutchison

highlighter: rouge
markdown: kramdown
timezone: Europe/London
permalink: /:year/:month/:day/:title/
relative_permalinks: false
paginate: 5
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-github-metadata
- jekyll-octicons
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap

kramdown:
  parse_block_html: true

excerpt_separator: <!--more-->
drop_caps: false

exclude: [node_modules, assets/less]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      include_seo: true
  -
    scope:
      path: "archives"
      type: "pages"
    values:
      include_seo: true

# The base projects view this uses is based on the GitHub project
# https://github.com/github/personal-website
projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: true
    projects:
    - dhutchison.github.io
    - davidhutchison.scot
    - homepi
    - MWVisualisation
